version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ds_lab_react_gem
      POSTGRES_PASSWORD: password

  app:
    depends_on:
      - "postgres"
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/dslab
      - gems:/gems
    stdin_open: true
    tty: true

volumes:
  gems:
  pg_data:
