version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ds_lab_react_gem
      POSTGRES_PASSWORD: password

  app:
    depends_on:
      - "postgres"
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/ds_lab_react_gem
      - gems:/ds_lab_react_gem/bundle/gems
      - node_modules:/ds_lab_react_gem/node_modules
    stdin_open: true
    tty: true

  webpack:
    image: react-gem_app:latest
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    depends_on:
      - app
    volumes:
      - .:/app
      - node_modules:/ds_lab_react_gem/node_modules

volumes:
  gems:
  pg_data:
  node_modules:
